"""
Pydantic models for Note API endpoints.
Location: backend/app/models/note.py
"""

from pydantic import BaseModel, Field
from typing import Optional


class NoteCreateRequest(BaseModel):
    """Request body for creating a new note."""
    file_id: str = Field(..., description="UUID generated by discovery endpoint")
    title: str = Field(..., min_length=1, max_length=500)
    content: str = Field(..., description="Markdown content")
    url: Optional[str] = Field(None, description="Original source URL")
    
    class Config:
        json_schema_extra = {
            "example": {
                "file_id": "550e8400-e29b-41d4-a716-446655440000",
                "title": "Introduction to Neural Networks",
                "content": "# Neural Networks\n\nBasic concepts...",
                "url": "https://en.wikipedia.org/wiki/Neural_network"
            }
        }


class NoteUpdateRequest(BaseModel):
    """Request body for updating an existing note."""
    title: Optional[str] = Field(None, min_length=1, max_length=500)
    content: Optional[str] = Field(None, description="Updated markdown content")
    
    class Config:
        json_schema_extra = {
            "example": {
                "title": "Updated Title",
                "content": "# Updated Content\n\nNew information..."
            }
        }


class NoteResponse(BaseModel):
    """Response model for note operations."""
    file_id: str
    title: str
    url: Optional[str] = None
    storage_path: str = Field(..., description="Path in Supabase Storage bucket")
    version_id: Optional[str] = Field(None, description="S3 version ID if versioning enabled")
    created_at: str  # ISO datetime string
    updated_at: str  # ISO datetime string
    size_bytes: int
    
    class Config:
        json_schema_extra = {
            "example": {
                "file_id": "550e8400-e29b-41d4-a716-446655440000",
                "title": "Introduction to Neural Networks",
                "url": "https://en.wikipedia.org/wiki/Neural_network",
                "storage_path": "notes/550e8400-e29b-41d4-a716-446655440000.md",
                "version_id": "v1.0.0",
                "created_at": "2024-11-23T10:00:00Z",
                "updated_at": "2024-11-23T10:00:00Z",
                "size_bytes": 1024
            }
        }


class NoteContentResponse(BaseModel):
    """Response model for retrieving note content."""
    file_id: str
    title: str
    content: str
    url: Optional[str] = None
    storage_path: str
    version_id: Optional[str] = None
    created_at: str  # ISO datetime string
    updated_at: str  # ISO datetime string
    size_bytes: int