"""
FastAPI endpoints for note management.
Location: backend/app/api/notes.py

Endpoints:
- POST   /api/notes          - Create new note
- GET    /api/notes/{id}     - Retrieve note
- PUT    /api/notes/{id}     - Update note
- DELETE /api/notes/{id}     - Delete note
- GET    /api/notes          - List all notes
"""

from fastapi import APIRouter, HTTPException, status
from typing import List
from app.schemas.note import (
    NoteCreateRequest,
    NoteUpdateRequest,
    NoteResponse,
    NoteContentResponse
)
from app.services.note import note_service

router = APIRouter(prefix="/notes", tags=["notes"])


@router.post("", response_model=NoteResponse, status_code=status.HTTP_201_CREATED)
async def create_note(request: NoteCreateRequest):
    """
    Create a new note in Supabase Storage.
    
    The file_id should be generated by the discovery endpoint when the user
    adds a source via the extension.
    """
    try:
        metadata = await note_service.create_note(
            file_id=request.file_id,
            title=request.title,
            content=request.content,
            url=request.url
        )
        
        return NoteResponse(
            file_id=metadata["file_id"],
            title=metadata["title"],
            url=metadata.get("url"),
            storage_path=metadata["storage_path"],
            version_id=None,  # Supabase versioning handles this automatically
            created_at=metadata["created_at"],
            updated_at=metadata["updated_at"],
            size_bytes=metadata["size_bytes"]
        )
    
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=str(e)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create note: {str(e)}"
        )


@router.get("/{file_id}", response_model=NoteContentResponse)
async def get_note(file_id: str):
    """
    Retrieve a note's content and metadata by file_id.
    """
    try:
        data = await note_service.get_note(file_id)
        
        return NoteContentResponse(
            file_id=data["file_id"],
            title=data["title"],
            content=data["content"],
            url=data.get("url"),
            storage_path=data["storage_path"],
            version_id=None,
            created_at=data["created_at"],
            updated_at=data["updated_at"],
            size_bytes=data["size_bytes"]
        )
    
    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Note with file_id '{file_id}' not found"
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve note: {str(e)}"
        )


@router.put("/{file_id}", response_model=NoteResponse)
async def update_note(file_id: str, request: NoteUpdateRequest):
    """
    Update an existing note. Supabase Storage automatically versions the file.
    
    You can update the title, content, or both.
    """
    try:
        metadata = await note_service.update_note(
            file_id=file_id,
            content=request.content,
            title=request.title
        )
        
        return NoteResponse(
            file_id=metadata["file_id"],
            title=metadata["title"],
            url=metadata.get("url"),
            storage_path=metadata["storage_path"],
            version_id=None,
            created_at=metadata["created_at"],
            updated_at=metadata["updated_at"],
            size_bytes=metadata["size_bytes"]
        )
    
    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Note with file_id '{file_id}' not found"
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update note: {str(e)}"
        )


@router.delete("/{file_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_note(file_id: str):
    """
    Delete a note from Supabase Storage.
    
    Note: This permanently deletes the note. If versioning is enabled,
    old versions may still be accessible through Supabase dashboard.
    """
    try:
        await note_service.delete_note(file_id)
        return None
    
    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Note with file_id '{file_id}' not found"
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete note: {str(e)}"
        )


@router.get("", response_model=List[NoteResponse])
async def list_notes(limit: int = 100):
    """
    List all notes (metadata only, no content).
    
    Useful for displaying a list of available notes in the UI.
    """
    try:
        notes = await note_service.list_notes(limit=limit)
        
        return [
            NoteResponse(
                file_id=note["file_id"],
                title=note["title"],
                url=note.get("url"),
                storage_path=note["storage_path"],
                version_id=None,
                created_at=note["created_at"],
                updated_at=note["updated_at"],
                size_bytes=note["size_bytes"]
            )
            for note in notes
        ]
    
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to list notes: {str(e)}"
        )